streetteam/docker-images

python-3.5.3-slim-mjml/Dockerfile

Needed for pypi requirements available only via `git+git://` protocol

NAMB-368 apt-get git

---

circleci-base/Dockerfile
circleci-deploy/Dockerfile

The debs the python repo builds have changed, but you can still install
previous versions.
Hence installing python-disutils would install 3.6.5
Which would conflict with the other packages upgraded to 3.6.7
note the differing package numbers in the output below
```
```Step 8/23 : RUN apt-cache policy python3-lib2to3 python3-distutils python3.6 python3.6-venv python3.6-dev
---> Running in c9c396f45399
python3-lib2to3:
Installed: (none)
Candidate: 3.6.5-3~16.04.york0.2
Version table:
3.6.5-3~16.04.york0.2 500
500 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main amd64 Packages
python3-distutils:
Installed: (none)
Candidate: 3.6.5-3~16.04.york0.2
Version table:
3.6.5-3~16.04.york0.2 500
500 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main amd64 Packages …

Change python-distutils -> libpython3.6-stdlib

---

circleci-fullstack/Dockerfile

Why we change this?
--------
The latest version causes errors in our integration tests: https://circleci.com/gh/streetteam/root/325664

hardcode mailcacher version 0.6.5

---

circleci-base/Dockerfile

**Why**
We're upgrading node in https://github.com/streetteam/root/pull/10701
**What**

GK-46 Match the node version we preload w/ root

---

circleci-base/Dockerfile

We need unzip for tfenv
to test:
- do `docker build circleci-base`
- run `docker run -it {NEW IMAGE ID}`
then when you are in the container,
- `git clone https://github.com/tfutils/tfenv.git ~/.tfenv && \
sudo ln -s ~/.tfenv/bin/* /usr/local/bin`
- `sudo tfenv install 0.12.5`, then `terraform version` should show 0.12.5

install unzip for tfenv

---

.circleci/config.yml
circleci-deploy/Dockerfile
circleci-fullstack/Dockerfile

- CI nightly job is failing after we removed ECS cluster: https://circleci.com/gh/streetteam/docker-images/689
- Using tfenv to install terraform

remove apex and updated terraform install to use tfenv

---

circleci-base/Dockerfile

to test:
- run `docker build circleci-base`
- run `docker run -it {IMAGENAME}`
- when you are in the container, run `heroku plugins`, you should see both `heroku-repo` and `heroku-releases-retry`

install heroku plugins on docker image

---

circleci-base/Dockerfile

To test:
- run `docker build circleci-base --tag circleci-base`
- run `docker run -it circleci-base:latest`
- when you are in the container, run `sudo pip install apache-airflow[postgres,password,crypto,celery,rabbitmq]`, there should be no error

install airflow deps

---

circleci-base/Dockerfile

needed for pycurl
https://stackoverflow.com/questions/46290556/installing-pycurl-with-fatal-error-gnutls-gnutls-h-no-such-file-or-directory

Add libgnutls28-dev apt dep

---

circleci-base/Dockerfile

To test:
- run `docker build circleci-base --tag circleci-base`
- run `docker run -it circleci-base:latest`
when you are in the container, run
`pg_dump --version`
`psql --version`
they should both output 11.5

upgrade pg_client version to 11

---

circleci-fullstack/Dockerfile

This seems to be causing problem with installing gdal, if we are going to use circle-fullstack

do not remove build essentials

---

circleci-base/Dockerfile

Tested this here: https://github.com/streetteam/root/pull/13391/commits/fee84b5b8a89a12d29d44ff9e89743790eea8cbd
for some reason the build started failing due to missing libraries, this PR adds them here, so we don't install them all the time on CI :)

Add libglu1-mesa libxi6

---

circleci-deploy/Dockerfile
circleci-fullstack/Dockerfile

https://sentry.io/organizations/pollen/issues/1590766638/?referrer=slack
`Installation of terraform v0.12.17 successful. To make this your default version, run 'tfenv use 0.12.17'`
from https://circleci.com/gh/streetteam/docker-images/775

tfenv use command

---

.circleci/config.yml
circleci-deploy/Dockerfile

Since we are going to upload sourcemaps via terraform.
It's better to have sentry-cli available on the docker image, so we don't have to install it every time.
How to test:
- `docker build circleci-deploy`
- `docker run -it {image_id}`
- once in the container, do `sentry-cli`, the command should be available

install sentry-cli for circle-deploy

---

circleci-deploy/Dockerfile

- We need it because we run `psql` command in terraform
- To test: `docker build circleci-deploy --tag circle-deploy`
- then `docker run -it {img_id}`
- run `psql --help` in the container, it should not error

install psql client on deploy image

---

circleci-base/Dockerfile

So projects can benefit from latest long term support version.

[UNI-1622] Upgrade nodejs version to LTS

---

.circleci/config.yml
python-gdal/Dockerfile

example taken from: https://github.com/thinkWhere/GDAL-Docker/blob/develop/3.7-shippable/Dockerfile
But I have highly slimed down the image, as we do not need the extra stuff or python:3.7-stretch base image
- run `docker build python-gdal`
- run `docker run -it --entrypoint /bin/bash {image_id}`
- run `gdal-config --version` within the container

Added docker image for python-gdal

---

python-gdal/Dockerfile

Pycurl needs this package due to `src/pycurl.h:191:13: fatal error: gnutls/gnutls.h: No such file or directory`

Install libgnutls28-dev

---

python-gdal/Dockerfile
python-psql/Dockerfile

Using `--no-install-requires` limits what's being installed.
Smushing all run commands into one makes cleanup easier; we don't need
to keep cache for apt between images.
Overall these two changes lower the size of this image from 620MB to
511MB.

UNI-2501: Small optimisation for python-psql + postgis removal

---

circleci-deploy/Dockerfile

This is needed to deploy our custom Vercel terraform provider.

Vercel: add custom terraform provider to the deploy image

---

circleci-deploy/Dockerfile

Reverts streetteam/docker-images#94
We have now published the provider, this plugin is not needed

Revert "Vercel: add custom terraform provider to the deploy image"
